version: '3'
volumes:
  database:
    driver: local
services:
  fatbot:
    build: .
    restart: always
    env_file:
      - fatbot.env
    environment:
      - FATBOT_TELEGRAM_TOKEN
      - FATBOT_SAVE_PATH
      - FATBOT_WORD_COUNT
    depends_on:
      - mysql
    volumes:
      - ./dumps:/go/src/github.com/wallnutkraken/fatbot/dumps
    expose:
      - "1587"
  mysql:
    image: mysql:latest
    restart: always
    expose:
      - 3306
    env_file:
      - fatbot.env
    volumes:
      - database:/var/lib/mysql